<a href="https://colab.research.google.com/github/shruthits02/New_Repo1/blob/main/numpy_practice_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy Functions/methods:






In [ ]:
import numpy as np
import pandas as pd

# Reshape an array
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = np.reshape(arr, (3, 2))
print(reshaped_arr)

# Transpose an array
arr = np.array([[1, 2, 3], [4, 5, 6]])
transposed_arr = np.transpose(arr)
print(transposed_arr)

# Concatenate two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated_arr = np.concatenate((arr1, arr2))
print(concatenated_arr)

# Split an array into sub-arrays
arr = np.array([1, 2, 3, 4, 5, 6])
sub_arrays = np.split(arr, 3)
print(sub_arrays)

# Resize an array
arr = np.array([1, 2, 3])
resized_arr = np.resize(arr, (2, 2))
print(resized_arr)


[[1 2]
 [3 4]
 [5 6]]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
[[1 2]
 [3 1]]


In [ ]:
# Reshape an array
python_list = [1, 2, 3, 4, 5, 6]
arr = np.array(python_list)
reshaped_arr = np.reshape(arr, (3, 2))
print(reshaped_arr)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#how can we multiply every number in the list by a constant?
python_list = [1, 2, 3, 4, 5, 6]
#python_list=python_list +5
#python_list
arr = np.array(python_list)
arr = arr*3


In [ ]:
arr

array([ 3,  6,  9, 12, 15, 18])

In [ ]:
#how would we do it without a vectorized operation and data structure?
for i in range(0,len(python_list)):
  python_list[i] = python_list[i]*3
python_list

[3, 6, 9, 12, 15, 18]

In [ ]:
python_list*3

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [ ]:
#adding python lists vs adding numpy arrays
list_one = [1,2,3]
list_two = [4,5,6]
list_one + list_two
arr1 = np.array(list_one)
arr2 = np.array(list_two)
arr1 + arr2

array([5, 7, 9])

In [ ]:
#vectorized multiplication
arr1*arr2
np.dot(arr1,arr2)

32

In [ ]:
# Transpose an array
arr = np.array([[1, 2, 3], [4, 5, 6]])
transposed_arr = np.transpose(arr)
print(transposed_arr)
#print('original array')
#print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Concatenate two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated_arr = np.concatenate((arr1, arr2))
print(concatenated_arr)

[1 2 3 4 5 6]


In [ ]:
# Split an array into sub-arrays
arr = np.array([1, 2, 3, 4, 5, 6])
sub_arrays = np.split(arr, 6)
print(sub_arrays)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]


In [ ]:
np.array([[1,2,3]]) + np.array([[4],[5],[6]])

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [ ]:
import numpy as np

# Compute the exponential of array elements
arr = np.array([1, 2, 3])
exp_arr = np.exp(arr)
print(exp_arr)

# Compute the natural logarithI apologize for the incomplete response. Here are the remaining examples of mathematical functions:

# Compute the natural logarithm of array elements
arr = np.array([1, 2, 3])
log_arr = np.log(arr)
print(log_arr)

# Compute the sine of array elements
arr = np.array([0, np.pi/2, np.pi])
sin_arr = np.sin(arr)
print(sin_arr)

# Compute the cosine of array elements
cos_arr = np.cos(arr)
print(cos_arr)

# Compute the square root of array elements
arr = np.array([4, 9, 16])
sqrt_arr = np.sqrt(arr)
print(sqrt_arr)






[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[2. 3. 4.]


In [ ]:
np.sin(np.pi)

1.2246467991473532e-16

In [ ]:
np.exp(0)

1.0

In [ ]:
# Reshape an array
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = np.reshape(arr, (2, 3))
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Transpose an array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
transposed_arr = np.transpose(arr)
print(transposed_arr)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Concatenate two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated_arr = np.concatenate((arr1, arr2))
print(concatenated_arr)

[1 2 3 4 5 6]


In [ ]:
# Resize an array
arr = np.array([1, 2, 3])
resized_arr = np.resize(arr, (3, 3))
print(resized_arr)
np.fill_diagonal(resized_arr, 0)
print(resized_arr)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[0 2 3]
 [1 0 3]
 [1 2 0]]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr*3

array([[ 3,  6,  9],
       [12, 15, 18]])

Below is a demonstration of how pandas deals with strings mixed in with quantitative data.

In [ ]:
df = pd.DataFrame({'column 1': [6.5, 7.8, 9],'column 2':[5,8,10],'column 3':[5,8.2,'fifty-five']})
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   column 1  3 non-null      float64
 1   column 2  3 non-null      int64  
 2   column 3  3 non-null      object 
dtypes: float64(1), int64(1), object(1)
memory usage: 200.0+ bytes


In [ ]:
df.iloc[2]['column 3'] = 'sixty'
df

<ipython-input-44-acfb528a81f1>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[2]['column 3'] = 'sixty'


column 1  column 2    column 3
0       6.5         5           5
1       7.8         8         8.2
2       9.0        10  fifty-five

In [ ]:
df.iloc[2]['column 3'] = 'sixty'

<ipython-input-51-88bcfdcc448b>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[2]['column 3'] = 'sixty'


In [ ]:
df['column 3'][2] = 'sixty'

<ipython-input-45-bc95bc5d18f6>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['column 3'][2] = 'sixty'


In [ ]:
df

column 1  column 2 column 3
0       6.5         5        5
1       7.8         8      8.2
2       9.0        10    sixty

In [ ]:
df.iloc[0][2]

5

In the above scenario, the following implamentation simply won't work:

In [ ]:


# Example DataFrame
df = pd.DataFrame({'Number': ['1,000', '2,500', '3,750']})
df.info()
print(type(df.iloc[2]['Number']))
# Convert string-based column to float-based column
df['Number'] = df['Number'].str.replace(',', '').astype(float)

# Display the updated DataFrame
print(df)
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Number  3 non-null      object
dtypes: object(1)
memory usage: 152.0+ bytes
<class 'str'>
   Number
0  1000.0
1  2500.0
2  3750.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Number  3 non-null      float64
dtypes: float64(1)
memory usage: 152.0 bytes


In [ ]:
type(df.iloc[0][0])

numpy.float64

We'll benefit from the following function:

In [ ]:
import re

def contains_non_numeric(string):
    pattern = r'[^0-9,.]'
    return re.search(pattern, string) is not None


In [ ]:
print(contains_non_numeric('fifty-five'))
print(contains_non_numeric('1,000,200'))

True
False


Or...

In [ ]:
int('9,00k00'.replace(',',''))

ValueError: ignored

Using a Lambda function on multiple columns simultaneously:

In [ ]:
import pandas as pd

data = {'A': [1, 2, 3, 4, 5], 'B': [10, 20, 30, 40, 50]}
df = pd.DataFrame(data)

# Define the lambda function to operate on multiple columns
function = lambda row: row['A'] * 2 + row['B']

# Apply the lambda function to create the new column
df['C'] = df.apply(function, axis=1)

# Display the updated DataFrame
print(df)


   A   B   C
0  1  10  12
1  2  20  24
2  3  30  36
3  4  40  48
4  5  50  60


In [ ]:
#using NumPy vectorize to do an opperation across an entire column
#using NumPy select to map multiple conditions to multiple different columns
import pandas as pd
import numpy as np

data = {'A': [1, 2, 3, 4, 5], 'B': [10, 20, 30, 40, 50]}
df = pd.DataFrame(data)

# Define the conditions
conditions = [
    df['A'] < 3,
    df['A'] >= 3
]

# Define the functions corresponding to each condition
def function1(x):
    return x * 2

def function2(x):
    return x + 5

# Vectorize the functions
vectorized_function1 = np.vectorize(function1)
vectorized_function2 = np.vectorize(function2)

# Apply the functions based on the conditions and create the new column
df['C'] = np.select(conditions, [vectorized_function1(df['A']), vectorized_function2(df['B'])], default=np.nan)

# Display the updated DataFrame
print(df)


   A   B     C
0  1  10   2.0
1  2  20   4.0
2  3  30  35.0
3  4  40  45.0
4  5  50  55.0


In [ ]:
import pandas as pd
import numpy as np

data = {'A': [1, 2, 3, 4, 5], 'B': [10, 20, 30, 40, 50]}
df = pd.DataFrame(data)
df
# Define the conditions
conditions = [
    df['A'] < 3,
    df['A'] >= 3
]

# Define the functions corresponding to each condition
def function1(df):
    return df['A'] * 2 + df['B']

def function2(df):
    return df['A'] + df['B'] * 2

# Apply the functions based on the conditions and create the new column
df['C'] = np.select(conditions, [function1(df), function2(df)], default=np.nan)

# Display the updated DataFrame
print(df)


   A   B      C
0  1  10   12.0
1  2  20   24.0
2  3  30   63.0
3  4  40   84.0
4  5  50  105.0


In [ ]:
# Check if values in column 'A' are NaN
df['A'].isna()


0    False
1    False
2    False
3    False
4    False
Name: A, dtype: bool

In [ ]:
# Reshape an array
python_list = [1, 2, 3, 4, 5, 6]
list2 = [4,5,7,9,0,1]
arr = np.array(python_list)
arr2 = np.array(list2)
arr = np.reshape(arr, (6, 1))
arr2 = np.reshape(arr2, (6, 1))
stack = (np.column_stack((arr, arr2)))
stack

array([[1, 4],
       [2, 5],
       [3, 7],
       [4, 9],
       [5, 0],
       [6, 1]])

In [ ]:
np.where(stack < 3, stack, None)

array([[1, None],
       [2, None],
       [None, None],
       [None, None],
       [None, 0],
       [None, 1]], dtype=object)

In [ ]:
def unstack(a, axis=1):
    return np.moveaxis(a, axis, 0)

In [ ]:
unstack(stack)

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 7, 9, 0, 1]])

In [ ]:
a_list = list(range(0,500000))
b_list = list(range(500000,1000000))

for i in range(0,500000):
  if a_list[i] > 250000 and b_list[i] > 750000:
    del a_list[i]
    del b_list[i]
  else:
    continue

IndexError: ignored

In [ ]:
alist = []
for i in 'sfsadfsdfsdaf':
  alist.append(i)
print(sorted(alist))

['a', 'a', 'd', 'd', 'd', 'f', 'f', 'f', 'f', 's', 's', 's', 's']


In [ ]:
alist.remove('a')
alist

['s', 'f', 's', 'd', 'f', 's', 'd', 'f', 's', 'd', 'a', 'f']

In [ ]:
footballers_goals = {'Eusebio': 120, 'Cruyff': 104, 'Pele': 150, 'Ronaldo': 132, 'Messi': 125}

sorted_footballers_by_goals = sorted(footballers_goals.items(), key=lambda x:x[1], reverse=True)
sorted_footballers_by_goals

[('Pele', 150),
 ('Ronaldo', 132),
 ('Messi', 125),
 ('Eusebio', 120),
 ('Cruyff', 104)]